---

# aguia-pescadora-docker.yml

- name: aguia-pescadora-docker
  hosts: "all"
  become: true
  vars:
    docker__channel: ["stable"]

  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
    - role: "kibatic.traefik"
      tags: ["traefik"]
